### PR TITLE
Update dependencies and to Rust 2021

### LINKED ISSUE #1: Migrate to hyper 0.12
Consider migration to hyper 0.12 to get rid of deprecated tokio-core and other tokio crates and use https://github.com/tokio-rs/tokio instead

### PR DESCRIPTION
**Pull request by sourcefrog**
Fixes #1 

- [x] cargo fmt
- [x] Add all examples to a workspace
- [x] Use `dyn` and other Rust 2021 fixes
- [x] Fix broken test code
- [x] Put `dyn` keywords in generated code
- [x] Update to prost 0.11
- [x] Update to Rust 2021
- [x] Update bytes to 1.2
- [x] Update to Hyper 0.14
- [x] Update to Futures 0.3.25
- [x] Migrate from tokio-core to Tokio
- [x] Rewrite some things to `async` sugar for easier readability
- [x] Generate code using `quote!`: also more readable than format strings IMO
- [x] Fix URLs to be like `/twirp/twirp.example.haberdasher.Haberdasher/MakeHat` <https://twitchtv.github.io/twirp/docs/routing.html#http-routes>
- [x] Add me as co-author
- [x] Update repo URL to `sourcefrog/prost-twirp`
- [x] Add NEWS.md
- [x] Maybe remove `PTReq` as it's now trivial 
- [ ] Check README is up to date and that the quoted code fragments still work

### CODE REVIEW

**Comment by cretz** [comment]
I have basically abandoned this project. I just added a note on the README. I can merge this though no problem once you're done. 

Otherwise if you fork or remake this repo elsewhere, I would be happy to point to it from the README as its successor.

**Comment by sourcefrog** [comment]
OK, thanks, no problem.

Let me see if I can get it working and try it out in the place I wanted to
use it, then we can see.

I just put this up for visibility to anyone else who might come to this
bug.

Thanks for sharing the original code!

Martin

**Comment by sourcefrog** [comment]
Wow this turns out to be pretty large because the Hyper/etc APIs changed so much, but I'm planning to persist with it.

**Comment by sourcefrog** [comment]
I think this is basically OK: at least, all the examples run, it's on the current dependencies, and I feel pretty happy with how it looks.

If you like, rather than merging this, you could point to my repo and preferably add me as a crate owner.

**Comment by sourcefrog** [comment]
If you would like to read the diff and comment on anything it's welcome but don't feel obliged.

**Comment by cretz** [comment]
> If you like, rather than merging this, you could point to my repo and preferably add me as a crate owner.

I think this may be best, that way people aren't confused about maintenance here. What user should I add as Cargo owner? `sourcefrog`?

**Comment by sourcefrog** [comment]
Yes, thanks, https://crates.io/users/sourcefrog.

**Comment by cretz** [comment]
:+1: Am on holiday but I have set a reminder for the 28th.

**Comment by cretz** [comment]
I have added/invited you as a crate owner. Let me know if/when you're ready for me to update this README to direct people to https://github.com/sourcefrog/prost-twirp.

**Comment by sourcefrog** [comment]
Thanks @cretz.

By the way, am I missing something about the point of the embedding feature? It seems like it doesn't help much:

* prost_twirp is still a build-time dependency, to do the code gen, so build times will not be faster
* the code that's linked in is very similar, so binaries won't be smaller?
* Rust is quasi-statically linked so it doesn't make for any fewer deploy-time dependencies
* Most of the build time and code size is probably not from prost_twirp itself but rather the stack of hyper and tokio dependencies, and they'll be the same either way

I'm thinking of just dropping the feature but I wanted to make sure I wasn't missing something...

**Comment by cretz** [comment]
People like to reduce runtime dependencies. I just gave that option. This is a very tiny code gen, so forcing a runtime dependency just seemed a bit rude to me (like if cbindgen was a required runtime dependency or something). In retrospect, I may have done embedding by default, but there's code sharing benefits of course.

Sure we can always say that compile time optimization removes the need to reduce dependency count for small dependencies. I just don't want to leftpad people at runtime.

I don't mind if you remove, your project now :-)

**Comment by sourcefrog** [comment]
OK I'm going to publish this soon. 

I realized that instead of just updating the readme in your branch, it would be a bit nicer to transfer the repo, which will make the URLs redirect and so on. I realize it's very old and low traffic, but it's a bit nicer.

https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

If that's OK with you, you can transfer it to the new https://github.com/prost-twirp organization.

**Comment by cretz** [comment]
I'd rather update the README if that's ok, but you can copy stuff over and remove the "forked from" part of GH if you want. No prob. Just not wanting to completely remove the repo out of my personal org, even though it is admittedly abandoned and will be marked as such. If you feel strongly enough though, I guess I can.

**Comment by sourcefrog** [comment]
Oh sure, no problem at all. You can just update the readme to mine whenever you like.

I'll close this PR in a bit because we're not actually going to merge my branch into yours, then merge this to the main branch, and push to crates.io.

**Pull request closed without merging**
